# Generated by Django 5.2.1 on 2025-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microboss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('notion', 'Notion'), ('video', 'Video'), ('google_doc', 'Google Doc')], max_length=20)),
                ('resource_link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='toolkits/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='microboss.tag')),
            ],
        ),
    ]
