# Generated by Django 5.2.1 on 2025-05-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microboss', '0002_contenttype_tag_toolkit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField()),
                ('idea', models.TextField()),
            ],
        ),
    ]
